dataCountries[dataCountries=="Falkland Islands (Malvinas)"] <- "Falkland Islands"
dataCountries[dataCountries=="Turks and Caicos islands"] <- "Turks and Caicos Islands"
dataCountries[dataCountries=="Eswatini"] <- "eSwatini"
dataCountries[dataCountries=="Serbia"] <- "Republic of Serbia"
dataCountries[dataCountries=="Sao Tome and Principe"] <- "São Tomé and Principe"
dataCountries[dataCountries=="North Macedonia"] <- "Macedonia"
dataCountries[dataCountries=="Guinea Bissau"] <- "Guinea-Bissau"
dataCountries[dataCountries=="Democratic Republic of the Congo"] <- "Republic of the Congo"
dataCountries[dataCountries=="Cape Verde"] <- "Cabo Verde"
dataCountries[dataCountries=="Brunei Darussalam"] <- "Brunei"
dataCountries[dataCountries=="Bahamas"] <- "The Bahamas"